version: '3.9'

services:
  feedback:
    container_name: feedback
    image: feedback
    build:
      context: .
      dockerfile: ./Dockerfile
    networks:
      - mysqlnet
    ports:
      - 5002:5002
    volumes:
      - ./:/app

  mysqldb:
    container_name: mysqldb
    image: mysqldb
    environment:
      MYSQL_ROOT_PASSWORD: ####
      MYSQL_DATABASE: ####
      MYSQL_USER: ####
      MYSQL_PASSWORD: ####
    ports:
      - 3308:3306
    networks:
      - mysqlnet
    volumes:
      - mysql:/var/lib/mysql
      - mysql_config:/etc/mysql

volumes:
  mysql:
  mysql_config:

networks:
  mysqlnet: